/** @type {import('tailwindcss').Config} */
const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');

module.exports = {
    content: ['./src/**/*.js', './src/**/*.mdx'],
    darkMode: ['class', '[data-mode="dark"]'],
    theme: {
        borderRadius: {
            btn: defaultTheme.borderRadius.full,
            input: defaultTheme.borderRadius.full,
            tag: defaultTheme.borderRadius.full,
            card: defaultTheme.borderRadius.md,
            tooltip: defaultTheme.borderRadius.md,
            dialog: defaultTheme.borderRadius.md,
            avatar: '50%',
            fab: '50%',
        },
        colors: {
            white: '#fff',
            black: '#000',
            transparent: 'transparent',
            current: 'currentColor',
            gray: colors.stone,
            primary: colors.lime,
            'accent-1': colors.orange,
            'accent-2': colors.amber,
        },
        fontFamily: {
            headline: [
                'Charter',
                'Bitstream Charter',
                'Sitka Text',
                'Cambria',
                'serif',
            ],
            body: [
                'Inter',
                'Roboto',
                'Helvetica Neue',
                'Arial Nova',
                'Nimbus Sans',
                'Arial',
                'sans-serif',
            ],
        },
        fontSize: {
            xs: 'clamp(0.7rem, calc(0.81rem + -0.13vw), 0.78rem)',
            sm: 'clamp(0.94rem, calc(0.94rem + 0vw), 0.94rem)',
            base: 'clamp(1.13rem, calc(1.08rem + 0.22vw), 1.25rem)',
            l: 'clamp(1.35rem, calc(1.24rem + 0.55vw), 1.67rem)',
            xl: 'clamp(1.62rem, calc(1.41rem + 1.05vw), 2.22rem)',
            '2xl': 'clamp(1.94rem, calc(1.59rem + 1.77vw), 2.96rem)',
            '3xl': 'clamp(2.33rem, calc(1.77rem + 2.81vw), 3.95rem)',
            '4xl': 'clamp(2.8rem, calc(1.94rem + 4.28vw), 5.26rem)',
        },
        lineHeight: {
            headline: '1.2',
            body: '1.5',
        },
        letterSpacing: {
            headline: defaultTheme.letterSpacing.normal,
            body: defaultTheme.letterSpacing.normal,
            overline: defaultTheme.letterSpacing.wide,
        },
        fontWeight: {
            headline: '700',
            body: '400',
        },
        spacing: {
            '3xs': 'clamp(0.31rem, calc(0.31rem + 0vw), 0.31rem)',
            '2xs': 'clamp(0.56rem, calc(0.54rem + 0.11vw), 0.63rem)',
            xs: 'clamp(0.88rem, calc(0.85rem + 0.11vw), 0.94rem)',
            s: 'clamp(1.13rem, calc(1.08rem + 0.22vw), 1.25rem)',
            m: 'clamp(1.69rem, calc(1.62rem + 0.33vw), 1.88rem)',
            l: 'clamp(2.25rem, calc(2.16rem + 0.43vw), 2.5rem)',
            xl: 'clamp(3.38rem, calc(3.24rem + 0.65vw), 3.75rem)',
            '2xl': 'clamp(4.5rem, calc(4.33rem + 0.87vw), 5rem)',
            '3xl': 'clamp(6.75rem, calc(6.49rem + 1.3vw), 7.5rem)',
            '4xl': 'clamp(13.5rem, calc(12.98rem + 2.61vw), 15rem)',
            '3xs-2xs': 'clamp(0.31rem, calc(0.2rem + 0.54vw), 0.63rem)',
            '2xs-xs': 'clamp(0.56rem, calc(0.43rem + 0.65vw), 0.94rem)',
            'xs-s': 'clamp(0.88rem, calc(0.74rem + 0.65vw), 1.25rem)',
            's-m': 'clamp(1.13rem, calc(0.86rem + 1.3vw), 1.88rem)',
            'm-l': 'clamp(1.69rem, calc(1.4rem + 1.41vw), 2.5rem)',
            'l-xl': 'clamp(2.25rem, calc(1.73rem + 2.61vw), 3.75rem)',
            'xl-2xl': 'clamp(3.38rem, calc(2.81rem + 2.83vw), 5rem)',
            '2xl-3xl': 'clamp(4.5rem, calc(3.46rem + 5.22vw), 7.5rem)',
            '3xl-4xl': 'clamp(6.75rem, calc(3.88rem + 14.35vw), 15rem)',
        },
        zIndex: {
            drawer: '700',
            dialog: '800',
            dropdown: '900',
            toast: '950',
            tooltip: '1000',
        },
        measure: {
            hero: '20ch',
            page: '25ch',
            region: '30ch',
            section: '30ch',
            title: '20ch',
            body: '66ch',
            blockquote: '40ch',
        },
        maxWidth: { region: '1200px' },
    },
};
