export const error = ["simple404", "splitWithImage404", "bgImage404"];
export const blog = [
  "textGridBlog",
  "cardGridBlog",
  "imgGridBlog",
  "stackBlog",
  "leftBlog",
  "FeaturedTextGridBlog",
  "FeaturedMixedGridBlog",
  "FeaturedCardGridBlog",
];
export const contact = [
  "centeredContact",
  "splitLeftContact",
  "splitRightContact",
];
export const content = ["contentContent"];
export const cta = [
  "simpleCta",
  "simpleLeftCta",
  "simpleRightCta",
  "leftImageCta",
  "rightImageCta",
  "splitLeftCta",
  "splitRightCta",
  "tiles2LeftCta",
  "tiles2RightCta",
  "tiles3LeftCta",
  "tiles3RightCta",
  "leftBgCta",
  "centerBgCta",
  "rightBgCta",
  "leftGradientCta",
  "centerGradientCta",
  "rightGradientCta",
  "justifiedCta",
  "simpleNewsletterCta",
  "simpleLeftNewsletterCta",
  "simpleRightNewsletterCta",
  "leftImageNewsletterCta",
  "rightImageNewsletterCta",
  "splitLeftNewsletterCta",
  "splitRightNewsletterCta",
  "tiles2LeftNewsletterCta",
  "tiles2RightNewsletterCta",
  "tiles3LeftNewsletterCta",
  "tiles3RightNewsletterCta",
  "leftBgNewsletterCta",
  "centerBgNewsletterCta",
  "rightBgNewsletterCta",
  "leftGradientNewsletterCta",
  "centerGradientNewsletterCta",
  "rightGradientNewsletterCta",
  "justifiedNewsletterCta",
];
export const faq = [
  "offsetFaq",
  "accordionFaq",
  "inlineFaq",
  "blurbGrid2Faq",
  "blurbGrid3Faq",
  "cardGrid2Faq",
  "cardGrid3Faq",
];
export const info = [
  "leftImageInfo",
  "rightImageInfo",
  "cardGridInfo",
  "blurbGridInfo",
  "offsetGridInfo",
  "offsetListInfo",
  "listInfo",
];
export const footer = [
  "missionFooter",
  "missionDarkFooter",
  "missionPrimaryFooter",
  "missionBgFooter",
  "missionDarkBgFooter",
  "missionPrimaryBgFooter",
  "newsletterFooter",
  "newsletterDarkFooter",
  "newsletterPrimaryFooter",
  "newsletterBgFooter",
  "newsletterDarkBgFooter",
  "newsletterPrimaryBgFooter",
  "simpleFooter",
  "simpleDarkFooter",
  "simplePrimaryFooter",
  "simpleBgFooter",
  "simpleDarkBgFooter",
  "simplePrimaryBgFooter",
  "inlineFooter",
  "inlineDarkFooter",
  "inlinePrimaryFooter",
];
export const header = [
  "leftHeader",
  "rightHeader",
  "leftImageHeader",
  "rightImageHeader",
  "centerHeader",
  "leftInverseHeader",
  "rightInverseHeader",
  "leftImageInverseHeader",
  "rightImageInverseHeader",
  "centerInverseHeader",
];
export const hero = [
  "leftHero",
  "rightHero",
  "splitLeftHero",
  "splitRightHero",
  "angledTopLeftHero",
  "angledTopRightHero",
  "angledBottomLeftHero",
  "angledBottomRightHero",
  "tiles2LeftHero",
  "tiles2RightHero",
  "tiles3LeftHero",
  "tiles3RightHero",
  "centerImageHero",
  "leftBgHero",
  "centerBgHero",
  "rightBgHero",
  "leftGradientHero",
  "centerGradientHero",
  "rightGradientHero",
];
export const logoCloud = ["gridLogoCloud", "simpleLogoCloud", "splitLogoCloud"];
export const navbar = [
  "centeredNavbar",
  "spacedNavbar",
  "startNavbar",
  "endNavbar",
  "stackedNavbar",
];
export const portfolio = [
  "leftImagePortfolio",
  "rightImagePortfolio",
  "cardGrid2Portfolio",
  "coverPortfolio",
];
export const stats = [
  "simple3Stats",
  "simple4Stats",
  "imageLeftStats",
  "imageRightStats",
  "splitLeftStats",
  "splitRightStats",
  "descriptionStats",
];
export const testimonial = [
  "simpleQuoteTestimonials",
  "centeredQuoteTestimonials",
  "leftAvatarTestimonials",
  "rightAvatarTestimonials",
];
export const timeline = [
  "inlineStartTimeline",
  "inlineStaggeredTimeline",
  "blockStartTimeline",
  "blockStaggeredTimeline",
];

export const process = [];
export const pricing = [];
