[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' usefathom.com *.usefathom.com unpkg.com/website-carbon-badges@1.1.3/*"